# ===== Netlify build config (Momona Klubb) =====
[build]
  base    = "frontend"                 # run build inside /frontend
  publish = "build"                    # deploy /frontend/build
  command = "npm ci && npm run build"
  # TEMP: force builds while we fix config
  # (remove this line later if you want skip-unchanged)
  # ignore  = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- frontend"

[build.environment]
  NODE_VERSION = "20"                  # react-router v7 requires >=20
  CI = "false"                         # don't fail build on ESLint warnings
  # REACT_APP_API_URL = "https://<your-backend>.onrender.com/api"

# SPA routing (React Router)
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

# Caching for CRA assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Basic security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
